# vim: ft=yaml sw=2 ts=2

language: go

# enable database services
services:
  - mysql
  - postgresql

# create test database
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sqlxtest;'
  - psql -c 'create database sqlxtest;' -U postgres
  - go get github.com/mattn/goveralls

# go versions to test
go:
  - "1.8"
  - "1.9"
  - "1.10.x"

# environment to test everything at once;  we want to avoid build matrixes
env:
  - SQLX_MYSQL_DSN="travis:@/sqlxtest?parseTime=true"
  - SQLX_POSTGRES_DSN="postgres://postgres:@localhost/sqlxtest?sslmode=disable"
  - SQLX_SQLITE_DSN="$HOME/sqlxtest.db"

# run tests w/ coverage
script:
  - $GOPATH/bin/goveralls -service=travis-ci
